#todo: improve with docker container build/push and native image build/tests

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: shakesperean-pokedex-maven-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: ./mvnw compile
      - run:
          name: Unit tests
          command: ./mvnw test
      - run:
          name: Integration tests
          command: ./mvnw integration-test -Dskip.unit.test=true
      - save_cache:
          paths:
            - ~/.m2
          key: shakesperean-pokedex-maven-dependencies-{{ checksum "pom.xml" }}