version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: shakesperean-pokedex-quarkus-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: ./mvnw clean compile
      - save_cache:
          paths:
            - ~/.m2
          key: shakesperean-pokedex-quarkus-{{ checksum "pom.xml" }}
      - run:
          name: Unit tests
          command: ./mvnw test
      - run:
          name: Integration tests
          command: ./mvnw integration-test