version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u232-jdk-stretch
    steps:
      - checkout
      - run:
          name: JAVA_HOME configuration
          command: |
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Maven java version
          command: |
            env grep -i java
            $JAVA_HOME/bin/javac -version
            ./mvnw --version
      - restore_cache:
          key: shakesperean-pokedex-quarkus-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: ./mvnw clean compile
      - save_cache:
          paths:
            - ~/.m2
          key: shakesperean-pokedex-quarkus-{{ checksum "pom.xml" }}
      - run:
          name: Unit tests
          command: ./mvnw test