version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u232-jdk-stretch
    steps:
      - checkout
      - run:
          name: Env check
          command: env | grep -i java && ls $JAVA_HOME
      - run:
        name: Maven java version
        command: ./mvnw --version
      - restore_cache:
          key: shakesperean-pokedex-quarkus-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: ./mvnw clean compile
      - save_cache:
          paths:
            - ~/.m2
          key: shakesperean-pokedex-quarkus-{{ checksum "pom.xml" }}
      - run:
          name: Unit tests
          command: ./mvnw test