#todo: improve with docker container build/push and native image build/tests

version: 2.1

references:
  default_executor: &default_executor
    docker:
      - image: circleci/openjdk:11
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - repo-{{ .Branch }}-{{ .Revision }}
        - repo-{{ .Branch }}
        - repo    

jobs:
  checkout:
    <<: *default_executor
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  build:
    <<: *default_executor
    steps:
      - *restore_repo
      - run: ./mvnw clean package -Dskip.unit.test=true -Dskip.integration.test=true
      - save_cache:
          paths:
            - ~/.m2
          key: shakesperean-pokedex-maven-dependencies-{{ checksum "pom.xml" }}
  unit_tests:
    <<: *default_executor
    steps:
      - *restore_repo
      - run: ./mvnw test
      - run:
          name: Save unit test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit    
  integration_tests:
    <<: *default_executor
    steps:
      - *restore_repo
      - run: ./mvnw integration-test -Dskip.unit.test=true 
      - run:
          name: Save integration test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" ! -name '*failsafe-summary.xml' -exec cp {} ~/test-results/junit/ \;
          when: always 
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit              

  # build:
  #   docker:
  #     - image: circleci/openjdk:11
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: shakesperean-pokedex-maven-dependencies-{{ checksum "pom.xml" }}
  #     - run:
  #         name: Build
  #         command: ./mvnw clean package -DskipTests
  #     - run:
  #         name: Unit tests
  #         command: ./mvnw test
  #     - run:
  #         name: Integration tests
  #         command: ./mvnw integration-test -Dskip.unit.test=true
  #     - save_cache:
  #         paths:
  #           - ~/.m2
  #         key: shakesperean-pokedex-maven-dependencies-{{ checksum "pom.xml" }}
  #     - run:
  #         name: Save test results
  #         command: |
  #           mkdir -p ~/test-results/junit/
  #           find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
  #           find . -type f -regex ".*/target/failsafe-reports/.*xml" ! -name '*failsafe-summary.xml' -exec cp {} ~/test-results/junit/ \;
  #         when: always
  #     - store_test_results:
  #         path: ~/test-results
  #     - store_artifacts:
  #         path: ~/test-results/junit

workflows:
  shakesperean_pokedex:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - unit_tests:
          requires:
            - build            
      - integration_tests:
          requires:
            - build       